# Homework Assignment 2
You will be analyzing an xyz file for water (water.xyz) and measuring the distances between all the atoms in the molecule. The file is located in the data folder of your workshop materials. The output of your code should look like:

    O to O : 0.0
    O to H1 : 0.969
    O to H2 : 0.969
    H1 to O : 0.969
    H1 to H1 : 0.0
    H1 to H2 : 1.527
    H2 to O : 0.969
    H2 to H1 : 1.527
    H2 to H2 : 0.0

To do this you will need to use the distance formula. You will need to square stuff and take the square root. To take the square root, you will use a function from numpy, numpy.sqrt(). To square something, use ** notation. As in, 3**2 = 9.

In [1]:
import os
import numpy

In [2]:
water_distance = os.path.join('data','water.xyz')
print(water_distance)

data\water.xyz


In [7]:
data = numpy.genfromtxt(fname=water_distance, dtype='unicode', skip_header=2)

print(data)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [10]:
# need to seperate each column and split
atom = data[:,0]
print(atom)
coord = data[:,1:]
coord = coord.astype(numpy.float)
print(coord)

# my code:
x_str = data[:,1]
print(x_str)
y_str = data[:,2]
print(y_str)
z_str = data[:,3]
print(z_str)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
['0.000000' '-0.000000' '0.000000']
['-0.007156' '0.001486' '0.931026']
['0.965491' '-0.003471' '1.207929']


<ipython-input-10-41e5c4b38273>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coord = coord.astype(numpy.float)


In [5]:
x = x_str.astype(float)
print(x)
y = y_str.astype(float)
print(y)
z = z_str.astype(float)
print(z)

[ 0. -0.  0.]
[-0.007156  0.001486  0.931026]
[ 0.965491 -0.003471  1.207929]


In [39]:
length = len(x)

num_atoms = len(atom)

# (my work) nest two for loops instead of creating a for loop with two values! range should also be number of atoms not 
# total expected results 
for i in range(0,length):
    for j in range(0,length):
        eq = ((x[j] - x[i])**2) + ((y[j] - y[i])**2) + ((z[j] - z[i])**2)
        distance = numpy.sqrt(eq)
        print(F'{atom[i]} to {atom[j]} : {distance:.3f}')

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


In [40]:
# her code
for i in range(0,num_atoms):
    for j in range(0,num_atoms):
        x_distance = coord[i,0] - coord[j,0]
        y_distance = coord[i,1] - coord[j,1]
        z_distance = coord[i,2] - coord[j,2]
        distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        print(F'{atom[1]} to {atom[j]} : {distance:.3f}')

H1 to O : 0.000
H1 to H1 : 0.969
H1 to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H1 to O : 0.969
H1 to H1 : 1.527
H1 to H2 : 0.000


End of homeowkr assignment; beginning of lesson 3.

In [41]:
# Modify code to only print atoms that are actually bonding using arbitrary rule that distance must be less than 1.527 for 
# bonding atoms. (modified my own code)

for i in range(0,length):
    for j in range(0,length):
        eq = ((x[j] - x[i])**2) + ((y[j] - y[i])**2) + ((z[j] - z[i])**2)
        distance = numpy.sqrt(eq)
        if 0 < distance < 1.5:   # could also write if distance < 1.5 and distance > 0:
            print(F'{atom[i]} to {atom[j]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H2 to O : 0.969


In [49]:
# Use condition that i < j to prevent duplicating distances. 
for i in range(0,length):
    for j in range(0,length):
        if i < j:
            eq = ((x[j] - x[i])**2) + ((y[j] - y[i])**2) + ((z[j] - z[i])**2)
            distance = numpy.sqrt(eq)
            if 0 < distance < 1.5:
                print(F'{atom[i]} to {atom[j]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


## Writing and using functions

In [43]:
# function - code that does a particular mathematical operation (ex: numpy.sqrt is a function someone else has written)
# want a function to do just one mathematical operation

# def  function_name(parameters):
    # ** body of your function **
    # ** write code using parameters to calculate something **
    # return value_to_return

In [45]:
# function must take simplest inputs/outputs you can think of; don't overthink!
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [48]:
calculate_distance([0, 0, 0], [0, 0,1])

1.0

In [47]:
calculate_distance([0, 0, 0], [1, 1,1])

1.7320508075688772

In [53]:
# must use coordinate slice for this; x,y,z slices would not work
for i in range(0,length):
    for j in range(0,length):
        if i < j:
            distance = calculate_distance(coord[i], coord[j])
            if 0 < distance < 1.5:
                print(F'{atom[i]} to {atom[j]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [55]:
# Write a function to check and see if a distance is a bond.
# Boolean operators in python are True and False
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance < 1.5:
        return True
    else: 
        return False

In [56]:
bond_check(1.7)

False

In [57]:
bond_check(1.2)

True

In [58]:
bond_check(-50)

False

In [59]:
# Modify bond_check function to take a minimum and a maximum length as an input.
# Python will now give error if min and max are not specified.
def bond_check(atom_distance, min_length, max_length):
    if atom_distance > min_length and atom_distance < max_length:
        return True
    else: 
        return False

In [60]:
bond_check(1.7,0,2)

True

In [61]:
bond_check(1.7)

TypeError: bond_check() missing 2 required positional arguments: 'min_length' and 'max_length'

In [65]:
# 0 and 1.5 are default min and max values
# write help documentation inside """
def bond_check(atom_distance, min_length=0, max_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maimum: 1.5 angstroms
    """
    if atom_distance > min_length and atom_distance < max_length:
        return True
    else: 
        return False

In [66]:
bond_check(1.7)

False

In [67]:
bond_check(1.7,max_length=2.0)

True

In [68]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(atom_distance, min_length=0, max_length=1.5)
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maimum: 1.5 angstroms



In [69]:
for i in range(0,length):
    for j in range(0,length):
        if i < j:
            distance = calculate_distance(coord[i], coord[j])
            if bond_check(distance) is True:
                print(F'{atom[i]} to {atom[j]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [72]:
# Write a new function called open_xyz that opens and processes an xyz file. Your function should accept a filepath for the
# input.

#my code:
def open_xyz(filename):
    data = numpy.genfromtxt(fname=filename, dtype='unicode', skip_header=2)
    atom = data[:,0]
    coord = data[:,1:]
    coord = coord.astype(numpy.float)
    length = len(atom)
    for i in range(0,length):
        for j in range(0,length):
            if i < j:
                distance = calculate_distance(coord[i], coord[j])
                if bond_check(distance) is True:
                    print(F'{atom[i]} to {atom[j]} : {distance:.3f}')
    return

In [73]:
open_xyz(water_distance)

O to H1 : 0.969
O to H2 : 0.969


<ipython-input-72-617f2c6bcdac>:8: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coord = coord.astype(numpy.float)


In [74]:
# her code:
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as string and the coordinates as floats.
    """
    data = numpy.genfromtxt(fname=filename, dtype='unicode', skip_header=2)
    atom = data[:,0]
    coord = data[:,1:]
    coord = coord.astype(numpy.float)
    return symbols, coord

In [81]:
import os 
import numpy

def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

def bond_check(atom_distance, min_length=0, max_length=1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs: distance, minimum length for bond, maximum length for bond
    Default: minimum: 0 angstroms, maimum: 1.5 angstroms
    """
    if atom_distance > min_length and atom_distance < max_length:
        return True
    else: 
        return False
    
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as string and the coordinates as floats.
    """
    data = numpy.genfromtxt(fname=filename, dtype='unicode', skip_header=2)
    atom = data[:,0]
    coord = data[:,1:]
    coord = coord.astype(numpy.float) #spyder and windows dislikes numpy; works with just float
    return atom, coord

file_location = os.path.join('data','water.xyz')
atom, coordinates = open_xyz(file_location)
num_atoms = len(atom)
for i in range(0,num_atoms):
    for j in range(0,num_atoms):
        if i < j:
            distance = calculate_distance(coord[i],coord[j])
            if bond_check(distance) is True:
                print(F'{atom[i]} to {atom[j]} : {distance:.3f}')

O to H1 : 0.969
O to H2 : 0.969


<ipython-input-81-4374e9a875df>:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coord = coord.astype(numpy.float) #spyder and windows dislikes numpy; works with just float
